---
title: "Übersicht"
subtitle: "Sozialwissenschaftliche Forschungsmethoden für Fortgeschrittene"
author: "**Dr. André Calero Valdez**"
date: ""
output:
  xaringan::moon_reader:
    seal: false
    css: ["default", "default-fonts", "hcic.css"]  
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
library(stringr)
library(glue)
options(htmltools.dir.version = FALSE)
```

## Sozialwissenschaftliche Forschungsmethoden für Fortgeschrittene
**Übersicht**
```{r agenda, echo=FALSE, results='asis'}
# Write a function to read find all html files and get their titles and create a list
files <- dir(pattern = ".html")
files <- files[!files %in% c("index.html")]
rmds <- dir(pattern = ".Rmd")
res <- "\n"
for (i in 1:length(files)) {
  matching_rmd <- str_replace(files[i], ".html", ".Rmd")
  title <- rmarkdown::yaml_front_matter(matching_rmd)$title
  res <- paste0(res, 
                glue(" {i} - {title} [Link]({files[i]})<br/>\n")
                )
}
cat(res)

# TODO: move figures to includegraphics
# TODO: separate topics in individual smaller chunks
```

